# Generated by Django 3.1.4 on 2020-12-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Date',
            new_name='date',
        ),
    ]
